//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCRepair_Soft_application.app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Equipment
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> client_id { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
