//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCRepair_Soft_application.app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Completed_Jobs
    {
        public int id { get; set; }
        public string name_job { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<int> job_id { get; set; }
        public Nullable<System.DateTime> completion_date { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Jobs Jobs { get; set; }
        public Uri ImagePreview
        {
            get
            {
                return new Uri(System.IO.Path.Combine(Environment.CurrentDirectory, Employees.photo ?? ""));
            }
        }
        public string NameWork
        {
            get
            {
                return name_job;
            }
        }
        public string SotrudnikName
        {
            get
            {
                return "ФИО: " + Employees.surname + " " + Employees.name + " " + Employees.patronymic;
            }
        }
        public string Date
        {
            get
            {
                return "Дата выполнения: " + completion_date;
            }
        }
        public string CostString
        {
            get
            {
                return "Процент от заказа: " + Employees.reward_percentage.ToString();
            }
        }
        public string CostString2
        {
            get
            {
                return "Стоимость: " + Jobs.salary.ToString();
            }
        }
        public string Sale
        {
            get
            {
                return "Вознагрождение: " + Jobs.salary * Employees.reward_percentage;
            }
        }
        public string NameWorking
        {
            get
            {
                return "Услуга " + Jobs.name;
            }
        }
    }
}
